In [32]:
import numpy as np
import gensim
import string
import networkx as nx

In [33]:
dataset=open("C:\\Users\\320052309\\code\\minorproject\\collapsed-dataset\\collapsed.edgelist", 'rb')
G=nx.read_edgelist(dataset)
nodelist = list(G.nodes)

In [34]:
print(nodelist)

['57154', '3309', '5879', '23568', '1432', '2004', '8945', '5469', '10014', '7037', '10672', '7046', '4627', '23405', '3329', '2885', '2734', '5966', '5747', '1605', '10252', '868', '648', '11171', '3654', '3315', '3476', '79840', '10458', '55971', '6764', '6461', '6714', '4851', '5664', '2549', '5829', '5295', '5871', '6416', '302', '3622', '4087', '23557', '5603', '7157', '5599', '6464', '5300', '4303', '7531', '678', '3981', '1278', '4209', '2771', '5581', '7186', '5594', '208', '9545', '4086', '58533', '6809', '3643', '5580', '1958', '6647', '6774', '5371', '4790', '5607', '6868', '1147', '9043', '10987', '6886', '2547', '8976', '4690', '5606', '9479', '1956', '6850', '939', '56913', '6050', '283', '1969', '10755', '613', '5716', '8440', '1832', '5663', '10728', '7189', '4615', '4088', '9344', '4691', '3685', '7040', '3091', '55294', '5467', '5970', '4214', '10049', '240', '5578', '6778', '102', '5604', '3688', '7414', '7132', '1386', '306', '51135', '7001', '5914', '960', '7428', 

In [40]:
embeddings_index = dict()
f = open('C:\\Users\\320052309\\code\\minorproject\\embeddings\\collapsed\\node2vec\\collapsed.embeddings',encoding="utf8")
line1 = f.readline()
vecs = int(line1.split()[0])
dims = int(line1.split()[1])
for line in f:
    values = line.split()
    geneid = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[geneid] = coefs
f.close()
print('Loaded %s node vectors.' % len(embeddings_index))

Loaded 2564 node vectors.


In [41]:
embedding_matrix = np.zeros((vecs, dims))
print(embedding_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [42]:
#print(type(embeddings_index["1"]))
#print(type(embedding_matrix[1]))
#embedding_matrix[1]=embeddings_index["1"]
for i in range(len(nodelist)):
    embedding_matrix[i]=embeddings_index[nodelist[i]]
#print(embedding_matrix.shape)
print(embedding_matrix)

[[-0.00710601  0.23685624 -0.1288882  ...  0.10436698 -0.10706212
  -0.18627965]
 [-0.08302686  0.00861955 -0.14009781 ... -0.28452232 -0.05849155
  -0.3081246 ]
 [ 0.00866714  0.20573857 -0.35425761 ... -0.15277281  0.01345323
  -0.26331091]
 ...
 [ 0.06554656  0.06221021  0.21317461 ...  0.10534059 -0.06705853
  -0.00567114]
 [ 0.01075825  0.32918936  0.09856132 ...  0.31500244 -0.17283966
   0.0944421 ]
 [-0.05412215  0.38241205  0.06245172 ... -0.04794119 -0.06339817
   0.13478763]]


In [43]:
def node2id(node):
    return nodelist.index(node)
def id2node(idx):
    return nodelist[idx]

In [45]:
infile = open("C:\\Users\\320052309\\code\\minorproject\\collapsed-dataset\\collapsed.edgelist", 'r')

edgelist = []
for line in infile:
    edge1 = line.split()
    #print(edge1)
    edge1[0] = node2id(edge1[0])
    edge1[1] = node2id(edge1[1])
    edgelist.append(edge1)
    
edgematrix = np.stack(edgelist)
          
type(edgematrix)

numpy.ndarray

In [46]:
train_split= 0.6*(len(edgematrix))
train_split = int(train_split)

test_split = 0.3*(len(edgematrix))
test_split = int(test_split)

val_split = 0.1*(len(edgematrix))
val_split = int(val_split)

print(test_split + train_split + val_split)

35937


In [47]:
train_edges = edgematrix[0:train_split]
print(train_edges)

[[   0    1]
 [   2    3]
 [   4    5]
 ...
 [   1 1036]
 [ 668 1034]
 [ 667  258]]


In [48]:
test_edges = edgematrix[train_split:train_split + test_split]
print(test_edges)

[[ 750 1029]
 [ 749 1232]
 [  29  686]
 ...
 [2092 2275]
 [2361  514]
 [2260 1622]]


In [49]:
val_edges = edgematrix[train_split + test_split:train_split + test_split + val_split]
print(val_edges)

[[2225  190]
 [1920 1160]
 [ 656 2084]
 ...
 [ 741 2540]
 [ 645 2548]
 [2538  448]]


In [50]:
print(len(train_edges))

21563


In [51]:
print(len(test_edges))

10781


In [52]:
print(len(val_edges))

3593


In [53]:
print(len(train_edges) + len(test_edges) + len(val_edges))

35937


In [54]:
dataset=open("C:\\Users\\320052309\\code\\minorproject\\collapsed-dataset\\neg_samples.edgelist", 'rb')
G=nx.read_edgelist(dataset)
nodelist = list(G.nodes)

In [55]:
print(nodelist)

['2530', '2948', '8893', '84248', '9856', '8851', '7716', '144717', '541468', '7832', '222484', '3364', '58', '10273', '5604', '5705', '5335', '161882', '5868', '23409', '7531', '2205', '4040', '4891', '11047', '9070', '641', '1649', '140885', '81559', '4211', '10540', '5204', '645', '2736', '25836', '6813', '676', '10212', '6464', '7804', '51196', '3273', '8795', '37', '23568', '320', '23636', '25970', '5817', '2243', '9344', '1906', '9025', '23741', '301', '10054', '7442', '3832', '3276', '7942', '311', '57026', '4520', '79736', '10657', '3818', '55967', '23154', '1909', '8813', '4926', '29108', '1191', '121504', '8763', '30815', '123803', '5307', '7159', '5478', '7450', '6742', '1195', '140576', '10664', '55752', '6453', '3678', '539', '5139', '3202', '4850', '5191', '8092', '9927', '2997', '5654', '3383', '10652', '5801', '9218', '5170', '1019', '1672', '20', '5465', '5818', '8646', '25898', '6832', '1002', '23648', '253725', '4047', '4086', '240', '3612', '2590', '9255', '6672', '

In [56]:
infile = open("C:\\Users\\320052309\\code\\minorproject\\collapsed-dataset\\neg_samples.edgelist", 'r')

edgelist = []
for line in infile:
    edge1 = line.split()
    #print(edge1)
    edge1[0] = node2id(edge1[0])
    edge1[1] = node2id(edge1[1])
    edgelist.append(edge1)
    
edgematrix = np.stack(edgelist)
          
type(edgematrix)


numpy.ndarray

In [57]:
train_split= 0.6*(len(edgematrix))
train_split = int(train_split)

test_split = 0.3*(len(edgematrix))
test_split = int(test_split)

val_split = 0.1*(len(edgematrix))
val_split = int(val_split)

print(test_split + train_split + val_split)

35940


In [58]:
train_edges_false = edgematrix[0:train_split]
print(train_edges_false)

[[   0    1]
 [   2    3]
 [   4    5]
 ...
 [2365 1739]
 [ 712 1321]
 [ 707 1283]]


In [59]:
test_edges_false = edgematrix[train_split:train_split + test_split]
print(test_edges_false)

[[  99 2480]
 [1297  697]
 [  14  426]
 ...
 [  21 1503]
 [ 434 1359]
 [ 722 1689]]


In [60]:
val_edges_false = edgematrix[train_split + test_split:train_split + test_split + val_split]
print(val_edges_false)

[[1866  569]
 [ 355  515]
 [2152 2338]
 ...
 [2102 2177]
 [ 742 1721]
 [2401 2513]]


In [61]:
print(len(train_edges_false))
print(len(test_edges_false))
print(len(val_edges_false))
print(len(train_edges_false) + len(test_edges_false) + len(val_edges_false))

21564
10782
3594
35940


In [64]:
# Generate bootstrapped edge embeddings (as is done in node2vec paper)
    # Edge embedding for (v1, v2) = hadamard product of node embeddings for v1, v2
def get_edge_embeddings(edge_list):
    embs = []
    for edge in edge_list:
        node1 = edge[0]
        node2 = edge[1]
        emb1 = embedding_matrix[node1]
        emb2 = embedding_matrix[node2]
        edge_emb = np.multiply(emb1, emb2)
        embs.append(edge_emb)
    embs = np.array(embs)
    return embs

In [65]:
# Train-set edge embeddings
pos_train_edge_embs = get_edge_embeddings(train_edges)
neg_train_edge_embs = get_edge_embeddings(train_edges_false)
train_edge_embs = np.concatenate([pos_train_edge_embs, neg_train_edge_embs])

# Create train-set edge labels: 1 = real edge, 0 = false edge
train_edge_labels = np.concatenate([np.ones(len(train_edges)), np.zeros(len(train_edges_false))])

# Val-set edge embeddings, labels
pos_val_edge_embs = get_edge_embeddings(val_edges)
neg_val_edge_embs = get_edge_embeddings(val_edges_false)
val_edge_embs = np.concatenate([pos_val_edge_embs, neg_val_edge_embs])
val_edge_labels = np.concatenate([np.ones(len(val_edges)), np.zeros(len(val_edges_false))])

# Test-set edge embeddings, labels
pos_test_edge_embs = get_edge_embeddings(test_edges)
neg_test_edge_embs = get_edge_embeddings(test_edges_false)
test_edge_embs = np.concatenate([pos_test_edge_embs, neg_test_edge_embs])

# Create val-set edge labels: 1 = real edge, 0 = false edge
test_edge_labels = np.concatenate([np.ones(len(test_edges)), np.zeros(len(test_edges_false))])

In [68]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import average_precision_score

In [69]:
# Train logistic regression classifier on train-set edge embeddings
from sklearn.linear_model import LogisticRegression
edge_classifier = LogisticRegression(random_state=0)
edge_classifier.fit(train_edge_embs, train_edge_labels)

C:\Users\320052309\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [70]:
# Predicted edge scores: probability of being of class "1" (real edge)
val_preds = edge_classifier.predict_proba(val_edge_embs)[:, 1]
val_roc = roc_auc_score(val_edge_labels, val_preds)
val_ap = average_precision_score(val_edge_labels, val_preds)

In [71]:
# Predicted edge scores: probability of being of class "1" (real edge)
test_preds = edge_classifier.predict_proba(test_edge_embs)[:, 1]
test_roc = roc_auc_score(test_edge_labels, test_preds)
test_ap = average_precision_score(test_edge_labels, test_preds)

In [73]:
print ('node2vec Validation ROC score: ', str(val_roc))
print ('node2vec Validation AP score: ', str(val_ap))
print ('node2vec Test ROC score: ', str(test_roc))
print ('node2vec Test AP score: ', str(test_ap))

node2vec Validation ROC score:  0.920038515502149
node2vec Validation AP score:  0.9164144634580973
node2vec Test ROC score:  0.9161135387453051
node2vec Test AP score:  0.9139899672138635
