In [1043]:
import numpy as np
import gensim
import string
import networkx as nx

In [1088]:
dataset=open("C:\\Users\\320052308\\minorproject\\blood-data-ohmnet\\edgelists\\neutrophil.edgelist", 'rb')
G=nx.read_edgelist(dataset)
nodelist1 = list(G.nodes)

In [1089]:
print((nodelist1))

['4790', '79155', '154796', '7408', '57154', '3309', '5879', '23568', '1855', '8312', '10206', '396', '10577', '4864', '5604', '8837', '10801', '9217', '5310', '87', '55366', '23310', '149041', '7327', '1432', '2004', '10664', '3146', '56254', '51322', '11051', '3066', '8945', '246184', '51434', '5469', '10014', '7037', '10672', '7046', '26227', '2885', '6602', '64599', '6772', '7852', '2624', '161882', '55832', '1832', '5501', '351', '23081', '3065', '4627', '2074', '6733', '249', '23405', '3329', '3915', '3912', '10933', '3837', '5335', '5921', '9516', '23327', '4869', '498', '1650', '3703', '1019', '1457', '672', '2355', '2887', '1499', '5494', '3275', '6256', '55696', '6729', '10197', '55689', '153090', '8454', '7879', '57403', '22955', '8467', '10987', '8607', '84661', '10565', '5499', '5568', '7319', '1029', '118', '3398', '54822', '22976', '10111', '4771', '6895', '51194', '1810', '1017', '6883', '4734', '6189', '6601', '5978', '1786', '53615', '7157', '2648', '2734', '5966', '1

In [1090]:
embeddings_index1 = dict()
f = open("C:\\Users\\320052308\\minorproject\\embeddings\\independent\\node2vec\\neutrophil.embeddings",encoding="utf8")
line1 = f.readline()
vecs1 = int(line1.split()[0])
dims1 = int(line1.split()[1])
for line in f:
    values = line.split()
    geneid = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index1[geneid] = coefs
f.close()
print('Loaded %s node vectors.' % len(embeddings_index1))

#print(embeddings_index1)

Loaded 2025 node vectors.


In [1091]:
embedding_matrix1 = np.zeros((vecs1, dims1))

for i in range(len(nodelist1)):
    embedding_matrix1[i]=embeddings_index1[nodelist1[i]]
#print(embedding_matrix.shape)
print(embedding_matrix1)

[[ 0.0420443  -0.02608267  0.42032436 ... -0.00693114 -0.16090323
  -0.28204498]
 [ 0.12808201  0.52395898  0.11463754 ...  0.05011927  0.03462606
  -0.24350314]
 [-0.14819229  0.24954517  0.16186795 ...  0.11310942 -0.28225794
  -0.18624046]
 ...
 [-0.16235024  0.23986469  0.02086055 ... -0.0591935   0.21018228
  -0.13888136]
 [ 0.11930748  0.03940047  0.12711127 ... -0.04807102  0.13915332
  -0.02139526]
 [-0.0290811   0.13681936  0.06943955 ... -0.00966877  0.10743595
  -0.04957994]]


In [1092]:
nodelist2 = []
embeddings_index2 = dict()
f = open("C:\\Users\\320052308\\minorproject\\embeddings\\ohmnet\\myeloid_internal_vectors.embedding",encoding="utf8")
line1 = f.readline()
vecs2 = int(line1.split()[0])
dims2 = int(line1.split()[1])
for line in f:
    values = line.split()
    geneid = values[0]
    nodelist2.append(geneid)
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index2[geneid] = coefs
f.close()
print('Loaded %s node vectors.' % len(embeddings_index2))

Loaded 2554 node vectors.


In [1093]:
print(len(nodelist2))

2554


In [1094]:
embedding_matrix2 = np.zeros((vecs2, dims2))

for i in range(len(nodelist2)):
    embedding_matrix2[i]=embeddings_index2[nodelist2[i]]
#print(embedding_matrix.shape)
print(embedding_matrix2)

[[ 8.37652478e-03  9.72018763e-02  1.18844556e-02 ... -5.66648953e-02
   1.07660033e-01  1.41709102e-02]
 [ 2.04956941e-05  5.59460372e-03  6.48029847e-04 ... -3.98889044e-03
   6.39756070e-03  1.16273481e-03]
 [ 2.54965872e-02  1.68453649e-01  1.59898102e-02 ... -4.52733710e-02
   1.28852919e-01  2.21839435e-02]
 ...
 [ 2.92076804e-02  2.30624631e-01  2.50824280e-02 ... -8.62478465e-02
   2.00869322e-01  3.02866716e-02]
 [ 2.51965337e-02  2.06830814e-01  2.12405045e-02 ... -7.93245062e-02
   1.82541981e-01  2.81748679e-02]
 [ 4.41624178e-03  1.05970643e-01  1.30720735e-02 ... -7.59436116e-02
   1.30178511e-01  1.72022451e-02]]


In [1095]:
nodelist3 = []
embeddings_index3 = dict()
f = open("C:\\Users\\320052308\\minorproject\\embeddings\\ohmnet\\myeloblast_internal_vectors.embedding",encoding="utf8")
line1 = f.readline()
vecs3 = int(line1.split()[0])
dims3 = int(line1.split()[1])
for line in f:
    values = line.split()
    geneid = values[0]
    nodelist3.append(geneid)
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index3[geneid] = coefs
f.close()
print('Loaded %s node vectors.' % len(embeddings_index3))

Loaded 2554 node vectors.


In [1096]:
print(nodelist3)

['myeloblast_NODE__55614', 'myeloblast_NODE__55612', 'myeloblast_NODE__55342', 'myeloblast_NODE__55611', 'myeloblast_NODE__27284', 'myeloblast_NODE__28996', 'myeloblast_NODE__4023', 'myeloblast_NODE__84919', 'myeloblast_NODE__10899', 'myeloblast_NODE__55294', 'myeloblast_NODE__5983', 'myeloblast_NODE__341', 'myeloblast_NODE__51065', 'myeloblast_NODE__3996', 'myeloblast_NODE__8694', 'myeloblast_NODE__348', 'myeloblast_NODE__3992', 'myeloblast_NODE__7518', 'myeloblast_NODE__165918', 'myeloblast_NODE__51283', 'myeloblast_NODE__55904', 'myeloblast_NODE__961', 'myeloblast_NODE__6794', 'myeloblast_NODE__6792', 'myeloblast_NODE__4734', 'myeloblast_NODE__2316', 'myeloblast_NODE__84869', 'myeloblast_NODE__3683', 'myeloblast_NODE__85458', 'myeloblast_NODE__291', 'myeloblast_NODE__4651', 'myeloblast_NODE__4650', 'myeloblast_NODE__3684', 'myeloblast_NODE__4659', 'myeloblast_NODE__57617', 'myeloblast_NODE__57610', 'myeloblast_NODE__30845', 'myeloblast_NODE__6478', 'myeloblast_NODE__2268', 'myelobla

In [1097]:
embedding_matrix3 = np.zeros((vecs3,dims3))

for i in range(len(nodelist3)):
    embedding_matrix3[i]=embeddings_index3[nodelist3[i]]
#print(embedding_matrix.shape)
print(embedding_matrix3)

[[-0.00928305  0.08906404  0.01279575 ... -0.10316301  0.14680155
   0.01678375]
 [-0.00127177  0.01616295  0.00160502 ... -0.0146932   0.01936373
   0.00485687]
 [ 0.00496419  0.03336686  0.00348051 ... -0.01034016  0.02759969
   0.0044893 ]
 ...
 [-0.01064575  0.1335613   0.01644972 ... -0.1308118   0.18575732
   0.02903482]
 [-0.00961077  0.12135303  0.01522327 ... -0.11768153  0.17091779
   0.02513776]
 [-0.01401173  0.10420451  0.01298642 ... -0.1227445   0.16324645
   0.02612053]]


In [1098]:
def node2id_1(node):
    return nodelist1.index(node)
def id2node_1(idx):
    return nodelist1[idx]

In [1099]:
def node2id_2(node):
    return nodelist2.index(node)
def id2node_2(idx):
    return nodelist2[idx]

In [1100]:
def node2id_3(node):
    return nodelist3.index(node)
def id2node_3(idx):
    return nodelist3[idx]

In [1270]:
embedding_matrix4 = np.zeros((vecs1, dims1))
for node in nodelist1:
    mainrep = embedding_matrix1[node2id_1(node)]
    if('myeloblast_NODE__' + node not in nodelist3):
        print('myeloblast_NODE__' + node )  
    else:
        level1rep = 2.5*embedding_matrix3[node2id_3('myeloblast_NODE__' + node)]
                                                    
    if('myeloid_stemcell_NODE__' + node not in nodelist2):
        print('myeloid_stemcell_NODE__' + node)  
    else:
        level2rep = 1.5*embedding_matrix2[node2id_2('myeloid_stemcell_NODE__' + node)] 
        
    level12rep = np.add(level1rep,level2rep)
    embedding_matrix4[node2id_1(node)] = np.add(mainrep, level12rep)
     
    
    
    

myeloblast_NODE__54977
myeloid_stemcell_NODE__54977
myeloblast_NODE__10316
myeloid_stemcell_NODE__10316
myeloblast_NODE__9048
myeloid_stemcell_NODE__9048
myeloblast_NODE__163702
myeloid_stemcell_NODE__163702


In [1271]:
print(embedding_matrix4)

[[ 0.03832637  0.94934532  0.53479579 ... -0.83406707  1.12234139
  -0.13796908]
 [ 0.13823044  1.22281909  0.19672752 ... -0.43778307  0.83076256
  -0.10587778]
 [-0.15060071  0.33627145  0.17586825 ...  0.01568626 -0.12661196
  -0.16922227]
 ...
 [-0.1447769   0.79484459  0.0902822  ... -0.4132445   0.84014296
  -0.05386418]
 [ 0.12792576  0.59835671  0.19929514 ... -0.44054339  0.80976735
   0.06986912]
 [-0.04125168  0.5340907   0.12288191 ... -0.36273519  0.65159177
   0.02353154]]


In [1272]:
'''f = open("C:\\Users\\320052308\\minorproject\\embeddings\\ohmnet\\enriched_basophil.tsv","w")
for i in embedding_matrix4:
    for j in i:
        string = str(j) + "\t"
        f.write(string)
    f.write("\n")
f.close()'''

'f = open("C:\\Users\\320052308\\minorproject\\embeddings\\ohmnet\\enriched_basophil.tsv","w")\nfor i in embedding_matrix4:\n    for j in i:\n        string = str(j) + "\t"\n        f.write(string)\n    f.write("\n")\nf.close()'

In [1273]:
def node2id(node):
    return nodelist.index(node)
def id2node(idx):
    return nodelist[idx]

In [1274]:
infile = open("C:\\Users\\320052308\\minorproject\\blood-data-ohmnet\\edgelists\\neutrophil.edgelist", 'r')

edgelist = []
for line in infile:
    edge1 = line.split()
    #print(edge1)
    edge1[0] = node2id_1(edge1[0])
    edge1[1] = node2id_1(edge1[1])
    edgelist.append(edge1)
    
edgematrix = np.stack(edgelist)
          
print(edgematrix)

[[   0    1]
 [   2    3]
 [   4    5]
 ...
 [ 237   73]
 [1155  471]
 [ 543 1252]]


In [1275]:
train_split= 0.6*(len(edgematrix))
train_split = int(train_split)

test_split = 0.3*(len(edgematrix))
test_split = int(test_split)

val_split = 0.1*(len(edgematrix))
val_split = int(val_split)

print(test_split + train_split + val_split)

26340


In [1276]:
train_edges = edgematrix[0:train_split]
print(train_edges)

[[   0    1]
 [   2    3]
 [   4    5]
 ...
 [  98  537]
 [ 707  837]
 [ 244 1971]]


In [1277]:
test_edges = edgematrix[train_split:train_split + test_split]
print(test_edges)

[[116 526]
 [751   0]
 [108  48]
 ...
 [284 145]
 [564 117]
 [212  51]]


In [1278]:
val_edges = edgematrix[train_split + test_split:train_split + test_split + val_split]
print(val_edges)

[[ 263 2015]
 [ 143  116]
 [1310  589]
 ...
 [ 237   73]
 [1155  471]
 [ 543 1252]]


In [1279]:
print(len(train_edges))

15804


In [1280]:
print(len(test_edges))

7902


In [1281]:
print(len(val_edges))

2634


In [1282]:
print(len(train_edges) + len(test_edges) + len(val_edges))

26340


In [1283]:
dataset=open("C:\\Users\\320052308\\minorproject\\blood-data-ohmnet\\edgelists\\n_neutrophil.txt", 'rb')
G=nx.read_edgelist(dataset)
nodelist = list(G.nodes)

In [1284]:
print(nodelist)

['2547', '4728', '9031', '5796', '6047', '7468', '2746', '2150', '11030', '5119', '6194', '5819', '3275', '1718', '79718', '3801', '8440', '10277', '81542', '7422', '51185', '3240', '6497', '5991', '8517', '7159', '6885', '538', '5518', '10869', '249', '7155', '5802', '79661', '3303', '54332', '4869', '54968', '22861', '8396', '10664', '10299', '2767', '1120', '3141', '4824', '26271', '23133', '23210', '3309', '23303', '8202', '23047', '55183', '54962', '6655', '5268', '7052', '10497', '6199', '79577', '283149', '3627', '6786', '6515', '51343', '4296', '1020', '5155', '1978', '11135', '23476', '241', '4952', '51196', '9218', '51499', '7358', '26610', '5578', '3936', '26272', '29965', '3146', '2887', '5524', '57679', '3297', '10902', '2946', '5870', '10938', '868', '9557', '285464', '9371', '6376', '2969', '659', '3039', '22821', '11328', '55145', '23513', '7494', '5867', '5607', '123169', '5245', '1387', '3725', '116985', '8725', '79017', '10253', '79158', '3667', '80824', '4843', '742

In [1285]:
infile = open("C:\\Users\\320052308\\minorproject\\blood-data-ohmnet\\edgelists\\n_neutrophil.txt", 'r')

edgelist = []
for line in infile:
    edge1 = line.split()
    #print(edge1)
    edge1[0] = node2id(edge1[0])
    edge1[1] = node2id(edge1[1])
    edgelist.append(edge1)
    
edgematrix = np.stack(edgelist)
          
type(edgematrix)


numpy.ndarray

In [1286]:
train_split= 0.6*(len(edgematrix))
train_split = int(train_split)

test_split = 0.3*(len(edgematrix))
test_split = int(test_split)

val_split = 0.1*(len(edgematrix))
val_split = int(val_split)

print(test_split + train_split + val_split)


26340


In [1287]:
train_edges_false = edgematrix[0:train_split]
print(train_edges_false)

[[   0    1]
 [   2    3]
 [   4    5]
 ...
 [1446  849]
 [1033 1923]
 [ 889 1132]]


In [1288]:
test_edges_false = edgematrix[train_split:train_split + test_split]
print(test_edges_false)

[[ 513 1016]
 [2018  365]
 [1666 1931]
 ...
 [2019 1241]
 [1716 1728]
 [ 418 1002]]


In [1289]:
val_edges_false = edgematrix[train_split + test_split:train_split + test_split + val_split]
print(val_edges_false)

[[1712   21]
 [1105 1385]
 [1457  443]
 ...
 [ 393 1125]
 [1891  411]
 [1724 1399]]


In [1290]:
print(len(train_edges_false))
print(len(test_edges_false))
print(len(val_edges_false))
print(len(train_edges_false) + len(test_edges_false) + len(val_edges_false))

15804
7902
2634
26340


In [1291]:
# Generate bootstrapped edge embeddings (as is done in node2vec paper)
    # Edge embedding for (v1, v2) = hadamard product of node embeddings for v1, v2
def get_edge_embeddings(edge_list):
    embs = []
    for edge in edge_list:
        node1 = edge[0]
        node2 = edge[1]
        emb1 = embedding_matrix4[node1]
        emb2 = embedding_matrix4[node2]
        edge_emb = np.multiply(emb1, emb2)
        embs.append(edge_emb)
    embs = np.array(embs)
    return embs

In [1292]:
# Train-set edge embeddings
pos_train_edge_embs = get_edge_embeddings(train_edges)
neg_train_edge_embs = get_edge_embeddings(train_edges_false)
train_edge_embs = np.concatenate([pos_train_edge_embs, neg_train_edge_embs])

# Create train-set edge labels: 1 = real edge, 0 = false edge
train_edge_labels = np.concatenate([np.ones(len(train_edges)), np.zeros(len(train_edges_false))])

# Val-set edge embeddings, labels
pos_val_edge_embs = get_edge_embeddings(val_edges)
neg_val_edge_embs = get_edge_embeddings(val_edges_false)
val_edge_embs = np.concatenate([pos_val_edge_embs, neg_val_edge_embs])
val_edge_labels = np.concatenate([np.ones(len(val_edges)), np.zeros(len(val_edges_false))])

# Test-set edge embeddings, labels
pos_test_edge_embs = get_edge_embeddings(test_edges)
neg_test_edge_embs = get_edge_embeddings(test_edges_false)
test_edge_embs = np.concatenate([pos_test_edge_embs, neg_test_edge_embs])

# Create val-set edge labels: 1 = real edge, 0 = false edge
test_edge_labels = np.concatenate([np.ones(len(test_edges)), np.zeros(len(test_edges_false))])

In [1293]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import average_precision_score

In [1294]:
# Train logistic regression classifier on train-set edge embeddings
from sklearn.linear_model import LogisticRegression
edge_classifier = LogisticRegression(random_state=0)
edge_classifier.fit(train_edge_embs, train_edge_labels)

C:\Users\320052308\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [1295]:
# Predicted edge scores: probability of being of class "1" (real edge)
val_preds = edge_classifier.predict_proba(val_edge_embs)[:, 1]
val_roc = roc_auc_score(val_edge_labels, val_preds)
val_ap = average_precision_score(val_edge_labels, val_preds)

In [1296]:
# Predicted edge scores: probability of being of class "1" (real edge)
test_preds = edge_classifier.predict_proba(test_edge_embs)[:, 1]
test_roc = roc_auc_score(test_edge_labels, test_preds)
test_ap = average_precision_score(test_edge_labels, test_preds)

In [1297]:
print ('ohmnet_blood_platelet Validation ROC score: ', str(val_roc))
print ('ohmnet_blood_platelet Validation AP score: ', str(val_ap))
print ('ohmnet_blood_platelet Test ROC score: ', str(test_roc))
print ('ohmnet_blood_platelet Test AP score: ', str(test_ap))

ohmnet_blood_platelet Validation ROC score:  0.9060110787672911
ohmnet_blood_platelet Validation AP score:  0.9005708580618164
ohmnet_blood_platelet Test ROC score:  0.9070850342025167
ohmnet_blood_platelet Test AP score:  0.9010824505216987
